const mongoose = require('mongoose');

const transactionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  type: { type: String, enum: ['income', 'expense'], required: true },
  amount: { type: Number, required: true, min: [0.01, 'Amount must be positive'] },
  category: { type: String, required: true },
  date: { type: Date, required: true },
  note: { type: String, default: '' },

  // multi-currency: the currency the record was actually entered in
  currency: { type: String, enum: ['INR', 'USD', 'EUR', 'GBP'], default: 'INR' },

  // set only if this transaction was auto-generated by a recurring rule
  recurringRuleId: { type: mongoose.Schema.Types.ObjectId, ref: 'RecurringRule', default: null },

  // base64 data URL of a scanned receipt photo (compressed client-side before upload)
  receiptImage: { type: String, default: '' },
}, { timestamps: true });

// supports list sort (by date) + search at scale
transactionSchema.index({ userId: 1, date: -1 });
transactionSchema.index({ note: 'text', category: 'text' });

module.exports = mongoose.model('Transaction', transactionSchema);
